CREATE TABLE Users
(
	[Id] NVARCHAR(100) PRIMARY KEY,
	[EmployeeId] INT UNIQUE,
	[Name] NVARCHAR(MAX) NOT NULL,
	[Email] NVARCHAR(MAX) NOT NULL,
	[Password] NVARCHAR(15) NOT NULL,
	[Designation] NVARCHAR(100) NOT NULL,
	[Role] INT NOT NULL
);

SELECT * FROM Users
DROP TABLE Users
